### ISSUE TITLE
Port Chromium DevTools extension to the Microsoft Edge extension store

### ISSUE THREAD

**Issue by brendyna** [vuejs/devtools#1155]
### What problem does this feature solve?
We on the Microsoft Edge team have received a significant number of requests from web developers looking for the VueJS browser dev tools extension in the Microsoft Edge extension store.

We'd love to host the VueJS extension there. Docs on how to publish it are here: https://developer.microsoft.com/en-us/microsoft-edge/extensions/.

Please let us (@EdgeDevTools) know if you run into issues or need any assistance at all.

### What does the proposed API look like?
No new APIs requested.

**Comment by p2well** [comment]
I fully support this initiative. The new Microsoft Edge browser is now based on Chromium and it would be excellent to get vue-devtools as extension for it.

**Comment by waynecz** [comment]
Second it, now (2020/03/23) on https://microsoftedge.microsoft.com/addons/search/vue?hl=zh-CN still has no result.

**Comment by GuoDapeng** [comment]
Critical Validations     2failure(s)
--
Product Policies1.1.3  Distinct Function & Value; Accurate RepresentationUnfortunately, we cannot test the product because the product's primary functions are not usable. Steps to reproduce: 1 - Launch Edge. 2 - Press on the Add-on button. 3 - Notice the Add-on displays the message "Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author." and no tab is added under the DevTools. Product Policies

1.5.2  Personal InformationBecause the product has access to personal information, a working link to a privacy policy must be provided in the “privacy policy URL” field when the product is submitted.

需要一个测试地址，需要提供隐私相关的东西。看样子还是自己 build 自己使用比较靠谱。不知道这个软件收据了啥。

**Comment by ostoh** [comment]
I support this and also hoping to be [available](https://microsoftedge.microsoft.com/addons/search/vue) soon.

**Comment by mehamednews** [comment]
Support this, I've been using chrome for years, But know that the Microsoft edge have all the features I was looking for without the chrome lagging and network problems, I'd like to be able to use vue devTools within the new browser!

**Comment by jonaskuske** [comment]
@mehamednews You can already use it in Edge, Edge allows you to install Chrome extensions from the Chrome Web Store. Releasing it as a proper Edge extension would only make it a bit more convenient

**Comment by rawrspace** [comment]
@jonaskuske You can install the extension but when you go to the developer console there is no tab for Vue so you are not able to use it in Edge. Given that the new Edge is based on chromium I imagine it is a small issue that is preventing it from working.

**Comment by jonaskuske** [comment]
@rawrspace You're right, interesting! I'm using Chromium Edge for some time now and I'm fairly certain that a couple months ago it still worked... (was using the Canary channel back then)

**Comment by rawrspace** [comment]
@jonaskuske just to clarify after the edit. Is it working in chromium Edge for you?

**Comment by rawrspace** [comment]
@jonaskuske Did you have to do anything special or just installed from chrome extension store?

**Comment by jonaskuske** [comment]
@rawrspace Hmm, don't think I did anything special, just installed from the Chrome Web Store.

Try to open a new tab and load `localhost` (or where ever the desired Vue app is running), then open Dev Tools. The "Vue" tab sometimes fails to load for me if I've opened Dev Tools in a tab before Vue was loaded on the page, but that has happened since forever.

You can also try enabling (and then disabling again if you want) the "Enable access to file URLs" toggle over at `edge://extensions`, then again try loading your app in a new tab. I've done that, but not sure if it did anything since as I mentioned I have since disabled this toggle again and it still works.

**Comment by rawrspace** [comment]
I closed all of my windows then launched and loaded my app. I then opened dev tools and the Vue panel was available.

To test I navigated to google.com with the panel still open and it dimmed. I closed developer tools and reopened them and Vue panel was gone, as expected since I was on google.com. I navigated back to my app and the panel appeared without me having to close or reopen dev tools.

The behavior I was seeing must have been a fluke. I haven't tested but potentially it happens when you first install the extension before you restart the browser.

In either case I think getting the extension from the chrome store seems fine and this is a low priority issue if not irrelevant.

**Comment by yoyoys** [comment]
> Product Policies1.1.3  Distinct Function & Value; Accurate RepresentationUnfortunately, we cannot test the product because the product's primary functions are not usable. Steps to reproduce: 1 - Launch Edge. 2 - Press on the Add-on button. 3 - Notice the Add-on displays the message "Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author." and no tab is added under the DevTools. Product Policies

他的意思是說要你提供這個 plugin 會如何使用收集到的資料的合約，剛好跟你想的相反。
白話來說就是要開發人員承諾在合理且有聲明的範圍內使用可能收集到的資料。

**Comment by yoyoys** [comment]
> Critical Validations     2failure(s)
> Product Policies1.1.3  Distinct Function & Value; Accurate RepresentationUnfortunately, we cannot test the product because the product's primary functions are not usable. Steps to reproduce: 1 - Launch Edge. 2 - Press on the Add-on button. 3 - Notice the Add-on displays the message "Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author." and no tab is added under the DevTools. Product Policies
> 1.5.2  Personal InformationBecause the product has access to personal information, a working link to a privacy policy must be provided in the “privacy policy URL” field when the product is submitted.
> 需要一个测试地址，需要提供隐私相关的东西。看样子还是自己 build 自己使用比较靠谱。不知道这个软件收据了啥。

他的意思是說要你提供這個 plugin 會如何使用收集到的資料的合約，剛好跟你想的相反。
白話來說就是要開發人員承諾在合理且有聲明的範圍內使用可能收集到的資料。

**Comment by kinkim** [comment]
In China, we cannot access Chrome extension without VPN. Chromium kernel has been used for Edge now, so it will be more convenient to install DevTools under Microsoft-Edged-Extensions

**Comment by Akryum** [comment]
I'm considering adding the devtools to more browsers after 6.0 is released.

**Comment by nagachaitanyalokam** [comment]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by ankurk91** [comment]
Someone published this
https://microsoftedge.microsoft.com/addons/detail/vuejs-devtools-ax/khampijcelfojpjcmmiibmhfkhacjhhj?hl=en-GB

Is it safe to use ?

**Comment by Akryum** [comment]
It's not published by us so I can't say if it's safe or not.

**Comment by nagachaitanyalokam** [comment]
Could you file a copyright infringement report [here](https://msrc.microsoft.com/report/infringement) for the concerned team to look into this?

**Comment by Akryum** [comment]
@nagachaitanyalokam I submitted the extension in the Partner Program but got rejected:

```
Product Policies

1.1.2 Distinct Function & Value; Accurate Representation
The product, including its listing, does not accurately represent the product and may mislead users. Your product may not use a name or icon that is too similar to that of other products.
```

**Comment by Akryum** [comment]
@nagachaitanyalokam I also just submitted an infringement notice to remove the existing extension that was not published by us: https://microsoftedge.microsoft.com/addons/detail/vuejs-devtools-ax/khampijcelfojpjcmmiibmhfkhacjhhj?hl=en-GB

**Comment by Akryum** [comment]
@nagachaitanyalokam Still rejected for obscure reasons...
![image](https://user-images.githubusercontent.com/2798204/158933405-fb6f3a9f-5496-41c7-b03a-969ccbb110fe.png)

**Comment by you227** [comment]
@Akryum The release of the plugin has been canceled. Before, because there was no plugin in Edge and you did not agree to release it, I released it to Edge myself. 
[https://github.com/vuejs/devtools/issues/1528](https://github.com/vuejs/devtools/issues/1528)

**Comment by Akryum** [comment]
> @Akryum The release of the plugin has been canceled. Before, because there was no plugin in Edge and you did not agree to release it, I released it to Edge myself. 
> [https://github.com/vuejs/devtools/issues/1528](https://github.com/vuejs/devtools/issues/1528)

Thanks! There will now be an official release 😉

**Comment by driver1998** [comment]
Friendly ping (again).
Still can't find vue devtools in Edge extensions store, are there still issues in submission?

**Comment by Akryum** [comment]
I didn't get anything back from them 🤷‍♂️

**Comment by sonakshimore** [comment]
Hey @Akryum!

Could you please share the store ID of your extension submission along with other additional information on a **"New support request"** form, on the [Request Help or Send Feedback](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team#request-help-or-submit-feedback) documentation?

I will make sure our team looks into this and help you at the earliest. Thank you!

**Comment by Akryum** [comment]
@sonakshimore Thank you for your help! I submitted to the help form

```We are trying to publish an official version of the Vue.js devtools but our submission is getting rejected with code 1.1.2 of Product Policies.

Store ID: 0RDCKC4FWHL7

See comment
https://github.com/vuejs/devtools/issues/1155#issuecomment-1068902414
 and following comments
```

Support request number: SR1538223702

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/164181843-d6664064-b681-425f-bbf3-e354f17487ee.png)

🤦‍♂️

**Comment by Akryum** [comment]
@sonakshimore support case was closed without resolution...

**Comment by sonakshimore** [comment]
@Akryum, let me see what best I can do to help you quickly. Thanks!

**Comment by Akryum** [comment]
The official Edge build is now published on the Edge store!
https://microsoftedge.microsoft.com/addons/detail/vuejs-devtools/olofadcdnkkjdfgjcmjaadnlehnnihnl

@sonakshimore Thank your for your help!
