### ISSUE TITLE
Since 3.2.41, devtools spends a lot of time in cleanupBuffer during component unmounts

### ISSUE THREAD

**Issue by Mario34** [vuejs/devtools#2002]
### Vue version

3.2.45

### Link to minimal reproduction

https://sfc.vuejs.org/#eNp9UstugzAQ/JWtL02kgJM+LhGJqPoJvfqSgClugm3ZC6mE+PeucUtJKvUEOzM7Y4/csxdr066VbMsyXzhlEbzE1u6FVo01DqGHTjqvjF6BkxUMUDnTwD3t3E+aV0NfLTV+kymfkGBOwsJoj6D8W20usAtOC3StXAqd8ZhLiTSgbOz5gJImgKze7Gk976czwDBknNCRPbaIBOXFWRWnnWCLyf4u/i0F2/uLwqLOeBTHxZ8Q6BJV0WJUkziwxP9ep0sq44JCl/ITlIbNer0WDHg04rPjzga2YrGYpDnY9MMbTfX2YYOcRsILtoURCRjdMcyC1YjWbzlvtT29p4VpeE4cd61G1cikNE3+mD6kT8+8VB7neCp9kxyduXjpKFGw1cycE0gFJk7SNZx0/4bdaK8Cb7g/oSFzEHqgAq4eQHhds6oEZqXqxgoFXgljq5GcFzp8AVvZ64o=

### Steps to reproduce

- Click the switch button to uninstall the components on the page
- Compare version 3.2.40 and version 3.2.45

![image](https://user-images.githubusercontent.com/42017165/206341576-398ed912-5cec-4505-8fb8-1fdce25aa82e.png)
![image](https://user-images.githubusercontent.com/42017165/206341711-3d663ea2-1f16-4c2f-a20b-5eedf4c53492.png)

### What is expected?

Component uninstallation time is consistent with the performance of version 3.2.40

### What is actually happening?

There is a significant time difference between version 3.2.45 and version 3.2.40 when components are unmount

**Comment by pavelhoral** [comment]
For me the slowdown happened when going from 3.2.37 and 3.2.38 but feels like it is the same as this issue...

The difference in my case is going from 100ms page update to 70s page update, thus changing developer experience to complete rubbish.

https://profiler.firefox.com/public/jw0yrsbxf8zccyf5qgapyp01h9smh0ztfnkd0g0/flame-graph/?globalTrackOrder=01&implementation=js&thread=1&v=8

**Comment by sohaha** [comment]
This problem bothered me for a long time, and I eventually found that downgrading the vue version to 3.2.40 improved it, but it was not a good solution.

**Comment by seanogdev** [comment]
Any chance of a beta release soon?

**Comment by mkierdev** [comment]
@LinusBorg @Akryum is there any progress about this issue? Devtools are not usable due to this bug, the performance slowdown is to much to handle any development (nuxt 3).

**Comment by LinusBorg** [comment]
In m understanding this issue was solved (and this this issue closed) with devtools 6.5.

Are you on that version?

I personally saw good performance aftrr updating to 6.5

**Comment by mkierdev** [comment]
I was on 6.5, however after your comment I disabled Performance monitoring and Update tracking in settings.

I can observe performance upgrade, however it's still not the DX I remember while developing on Vue 2. 
But disabling these options helped a lot and it seems that it can be finally usable.

Issue is still open so I assumed it wasn't implemented.

**Comment by LinusBorg** [comment]
I'll close this for now, but we will keep an eye on general performance anyway going forward. This particual area has been made more performant so we will need to look into other things from here on out.
