### ISSUE TITLE
Vuetools cannot be used after the Edge browser update

### ISSUE THREAD

**Issue by LingYzh** [vuejs/devtools#994]
After updating Edge to version 142.0.3595.53, launching Vue Devtools in devtools gets stuck on the logo screen.

**Comment by ZhangYunfan123** [comment]
I also have this issue and hope it can be resolved as soon as possible

**Comment by evan2306** [comment]
Same problem in Chrome v142

**Comment by angelacaldas** [comment]
Same problem since yesterday (11/05)
Edge v.142.0.3595.53

**Comment by BoYuanSu** [comment]
Same problem.

<img width="578" height="87" alt="Image" src="https://github.com/user-attachments/assets/bcb45520-b92b-456b-bc05-167f58226878" />

**Comment by BoYuanSu** [comment]
This is because the injectScript function in `devtools-panel.ts` encountered an error when using the browser API `chrome.devtools.inspectedWindow.eval`. I tried to fix this issue with the help of AI, and it recommended using the `chrome.scripting` API to inject the script. Now, the DevTools panel can open successfully, but it seems there are still some other issues.

<img width="744" height="663" alt="Image" src="https://github.com/user-attachments/assets/26715a50-47b6-4810-9002-27f894d54c08" />

<img width="830" height="335" alt="Image" src="https://github.com/user-attachments/assets/90638da6-cfb6-4221-a2c2-d6e13e76d217" />

<img width="1095" height="393" alt="Image" src="https://github.com/user-attachments/assets/398d6bd1-79df-4952-b93a-9dfc0b1b5923" />

**Comment by meduzen** [comment]
FYI React dev tools are [also broken](https://github.com/MicrosoftEdge/DevTools/issues/385) since the same update.

Edit: Vue dev tools working for me again since Edge 142.0.3595.80.

**Comment by ppeer** [comment]
SAME PROBLEM on edge Version 142.0.3595.53 (Officiële build) (64-bits)
vue devtools version: 7.7.7
chrome version Versie 141.0.7390.125 (Officiële build) (64-bits): NO PROBLEM working with vue-dev-tools

**Comment by baschnipke** [comment]
Just piling on here. It appears more than just vue devtools is broken for me though.

**Comment by KristofferHelgesen-NVE** [comment]
Im having the same issue

**Comment by Ashu-r** [comment]
The issue is solved on latest Edge update. Make sure to update to Version `142.0.3595.65+` by going to `edge://settings/help`

**Comment by sucodelarangela** [comment]
Working properly now

**Comment by allengordon011** [comment]
It's still not working for me.
Edge Version 142.0.3595.65 (Official build) (arm64)

<img width="629" height="436" alt="Image" src="https://github.com/user-attachments/assets/4b55e585-3c02-4b4d-a994-4082fdd2f414" />

**Comment by Nadahar** [comment]
> Edge Version 142.0.3595.65 (Official build) (arm64)

The version where it works for me is 142.0.3595.76 (Official build) (x86-64)

The fixed version probably isn't available for your installation source yet..?

**Comment by ppeer** [comment]
My experience: *.53 wasn't working *.80 is fine with vue-devtools.

**Comment by stefanovollono81** [comment]
On macOS, using Microsoft Edge version 142.0.3595.65, the extension (Versione 6.6.3) has stopped working. It completely freezes both the DevTools inspector and the browser tab where it’s running.

**Comment by Aftnos** [comment]
edge回退版本好麻烦，求求微软当个人吧

**Comment by yoyoys** [comment]
> edge回退版本好麻烦，求求微软当个人吧

我今天看已經更新了

**Comment by Aftnos** [comment]
> > edge回退版本好麻烦，求求微软当个人吧
> 
> 我今天看已經更新了

我仍然是 142.0.3595.80 版本，包含beta版本都不行，无论是vite还是纯vue3都不行，但是最扯的是edge自己的官网却可以成功识别出vue？？？？？？？？

<img width="2234" height="1257" alt="Image" src="https://github.com/user-attachments/assets/b81620ec-4d58-4033-a078-d6a4b0b33e24" />

**Comment by Aftnos** [comment]
> > > edge回退版本好麻烦，求求微软当个人吧
> > 
> > 
> > 我今天看已經更新了
> 
> 我仍然是 142.0.3595.80 版本，包含beta版本都不行，无论是vite还是纯vue3都不行，但是最扯的是edge自己的官网却可以成功识别出vue????????
> 
> <img alt="图像" width="2000" height="1257" src="https://private-user-images.githubusercontent.com/128480098/515183658-b81620ec-4d58-4033-a078-d6a4b0b33e24.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMzODU0NDksIm5iZiI6MTc2MzM4NTE0OSwicGF0aCI6Ii8xMjg0ODAwOTgvNTE1MTgzNjU4LWI4MTYyMGVjLTRkNTgtNDAzMy1hMDc4LWQ2YTRiMGIzM2UyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExN1QxMzEyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjFjZmFiODU0MDE1OWE3NjMzNzhkODNmYjk0YmNjMmUzYjAxOWU0MTE2Y2I5M2JmYjUyOTQzMzk5ZmI2NWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XkZzm2siYTECwloRx_Dr29mXTUAo-0lujaUl3LTESBw">

对此我只能说：微软你***了

**Comment by stefanovollono81** [comment]
It's work for me with:
Edge Version 142.0.3595.80 (arm64)
Vue.js devtools 6.6.3

**Comment by divlook** [comment]
It works after updating edge to the latest version

Edge Version 142.0.3595.80 (arm64)
Vue.js devtools 7.7.7
Vue.js devtools 6.6.4

**Comment by yoyoys** [comment]
> > > > edge回退版本好麻烦，求求微软当个人吧
> > > 
> > > 
> > > 我今天看已經更新了
> > 
> > 
> > 我仍然是 142.0.3595.80 版本，包含beta版本都不行，无论是vite还是纯vue3都不行，但是最扯的是edge自己的官网却可以成功识别出vue????????
> > <img alt="图像" width="2000" height="1257" src="https://private-user-images.githubusercontent.com/128480098/515183658-b81620ec-4d58-4033-a078-d6a4b0b33e24.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMzODU0NDksIm5iZiI6MTc2MzM4NTE0OSwicGF0aCI6Ii8xMjg0ODAwOTgvNTE1MTgzNjU4LWI4MTYyMGVjLTRkNTgtNDAzMy1hMDc4LWQ2YTRiMGIzM2UyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExN1QxMzEyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjFjZmFiODU0MDE1OWE3NjMzNzhkODNmYjk0YmNjMmUzYjAxOWU0MTE2Y2I5M2JmYjUyOTQzMzk5ZmI2NWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XkZzm2siYTECwloRx_Dr29mXTUAo-0lujaUl3LTESBw">
> 
> 对此我只能说：微软你***了

兄弟我測試是沒問題的喔，您要不裝個 devtool 用網頁版檔一下？

**Comment by Aftnos** [comment]
> > > > > edge回退版本好麻烦，求求微软当个人吧
> > > > 
> > > > 
> > > > 我今天看已經更新了
> > > 
> > > 
> > > 我仍然是 142.0.3595.80 版本，包含beta版本都不行，无论是vite还是纯vue3都不行，但是最扯的是edge自己的官网却可以成功识别出vue????????
> > > <img alt="图像" width="2000" height="1257" src="https://private-user-images.githubusercontent.com/128480098/515183658-b81620ec-4d58-4033-a078-d6a4b0b33e24.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMzODU0NDksIm5iZiI6MTc2MzM4NTE0OSwicGF0aCI6Ii8xMjg0ODAwOTgvNTE1MTgzNjU4LWI4MTYyMGVjLTRkNTgtNDAzMy1hMDc4LWQ2YTRiMGIzM2UyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExN1QxMzEyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjFjZmFiODU0MDE1OWE3NjMzNzhkODNmYjk0YmNjMmUzYjAxOWU0MTE2Y2I5M2JmYjUyOTQzMzk5ZmI2NWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XkZzm2siYTECwloRx_Dr29mXTUAo-0lujaUl3LTESBw">
> > 
> > 
> > 对此我只能说：微软你***了
> 
> 兄弟我测试是没问题的喔，您要不装个 devtool 用网页版档一下？

你的版本和我一样吗？我已经重装edge很多次了还是不行
